export default {
    products: [
        {
            _id:'1',
            name: 'Long Sleeve Thermal Women\'s Shirt',
            category: 'Tops',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Nike Sportswear Women\'s Woven Trousers',
            category: 'Bottoms',
            image: '/images/product-2.jpg',
            price: 80,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 44,
            countInStock: 16,
        },
        {
            _id:'3',
            name: 'Adidas Forum Low White Royal Blue',
            category: 'Shoes',
            image: '/images/product-3.jpg',
            price: 55,
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 24,
            countInStock: 8,
        },
        {
            _id:'4',
            name: 'Sportwear Windrunner Men\'s Hooded Jacket',
            category: 'Tops',
            image: '/images/product-4.jpg',
            price: 70,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 55,
            countInStock: 30,
        },
        {
            _id:'5',
            name: 'Reebok Club C Double Women\'s Shoes',
            category: 'Shoes',
            image: '/images/product-5.jpg',
            price: 90,
            brand: 'Reebok',
            rating: 4.6,
            numReviews: 15,
            countInStock: 12,
        },
        {
            _id:'6',
            name: 'Under Armour Hustle 5.0 Backpack',
            category: 'Bags',
            image: '/images/product-6.jpg',
            price: 39,
            brand: 'Under Armour',
            rating: 4.0,
            numReviews: 11,
            countInStock: 2,
        },
    ],
};